In [10]:
import json
import csv
import tweepy
import re
import nltk
from nltk.stem import WordNetLemmatizer
import pandas as pd
import GetOldTweets3 as got
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
import numpy as np

In [18]:
consumer_key = input()
consumer_secret = input()
access_key = input()
access_secret = input()

BZCiEnipIjwlIr5qdFawFL7Ka
UTHnBo6nzb5HhsQGoFxjEHBHArDAlT9VyXx8x98AObzpV6iArr
757468675414695936-wVM842i23t6yTUDhbwuKkH92LGnZRAq
TEFpzrCMH8aYl7YURiygG6Mgk76BAM9tLNWagI8JBAHiZ

In [20]:
june2019 = pd.read_json("june_iitb_tweets.json")
july2019 = pd.read_json("july_iitb_tweets.json")
aug2019 = pd.read_json("aug_iitb_tweets.json")
sept2019 = pd.read_json("sept_iitb_tweets.json")
oct2019 = pd.read_json("oct_iitb_tweets.json")
nov2019 = pd.read_json("nov_iitb_tweets.json")
dec2019 = pd.read_json("dec_iitb_tweets.json")
jan2020 = pd.read_json("jan2020_iitb_tweets.json")
feb2020 = pd.read_json("feb2020_iitb_tweets.json")
mar2020 = pd.read_json("mar2020_iitb_tweets.json")
apr2020 = pd.read_json("april2020_iitb_tweets.json")
may2020 = pd.read_json("may2020_iitb_tweets.json")
june2020 = pd.read_json("june2020_iitb_tweets.json")

In [25]:
frames = [june2019,july2019,aug2019,sept2019,oct2019,nov2019,dec2019,jan2020,feb2020,mar2020,apr2020,may2020,june2020]
tw_df = pd.concat(frames)
tweets_df = tw_df[['hashtags','timestamp','text','screen_name']]

In [32]:
tweets_df

,hashtags,timestamp,text,screen_name
0,[KathuaRape],2019-06-08 19:45:56,The humanities department of @iitbombay had co...,ajhay9
1,[],2019-06-08 19:12:35,"iit bombay problem heard , which salt is good ...",satishgmatt
2,[],2019-06-08 19:12:05,The energy burden that goes unaudited. Our wor...,ronitabardhan
3,[],2019-06-08 18:59:07,Dr. Puniyani is great and will fight for truth...,ChackoattukadJ
4,"[microplastics, worldoceansday]",2019-06-08 18:17:58,The study of @iitbombay shows that every brand...,CitizenKamran
...,...,...,...,...
2138,[],2020-06-10 01:00:25,Time to talk with New Yorker's on Social Dista...,prjeusa
2139,[],2020-06-10 00:32:20,"IIT Bombay is India’s top university, says 202...",DrRahul_G
2140,[],2020-06-10 00:30:22,from the abstract of this paper i have no idea...,jc96531326
2141,[],2020-06-10 00:17:39,That's a hella small sample size and a pretty ...,Techbropolis
2142,[SARSCov2],2020-06-10 00:15:48,"Marked differences in survival, drying time fo...",EricTopol

In [35]:
tweets_df = tweets_df.reset_index()

In [36]:
#check how many tweets were from one of the university handles
uni_tweets = tweets_df.loc[tweets_df['screen_name'].isin(['iitbombay','ecell_iitb','idc_iitb','edtechiitb'])]

In [37]:
uni_tweets['uni_handle'] = 1

C:\Users\KIRHIKAGURUMURTHY\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [38]:
uni_tweets
#uni_handle_list =  ['iitmadras','ecelliitm','vandemataramiit','iGEM_IITM','iitm_respark','domsiitmadras','emliitm','iitmbt','CFI_IITM','iitmfoundation']

,index,hashtags,timestamp,text,screen_name,uni_handle
58,58,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1
77,77,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1
141,141,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1
142,142,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1
226,226,[],2019-06-27 05:13:39,In order to create more awareness about solar ...,iitbombay,1
...,...,...,...,...,...,...
47391,448,[],2020-06-15 08:30:14,E-Cell IIT Bombay is proud to host a webinar w...,ecell_iitb,1
47701,758,[],2020-06-06 07:32:14,Kudos to team from IIT Bombay!\nhttps://www.hi...,iitbombay,1
48167,1224,[Proud_to_be_Indianpic],2020-06-12 11:53:56,"E-Cell, IIT Bombay congratulates Kiran Mazumda...",ecell_iitb,1
48480,1537,"[Connect_Learn_Grow, CAProgramLaunched, Regist...",2020-06-03 06:47:18,Presenting the E-Cell IIT Bombay's Campus Amba...,ecell_iitb,1
48659,1716,[],2020-06-11 09:19:45,IIT Bombay is ranked 3rd in engineering catego...,iitbombay,1

In [39]:
tweets_df['uni_handle'] = uni_tweets['uni_handle']

In [40]:
iitb = tweets_df.combine_first(tweets_df)
iitb

,index,hashtags,timestamp,text,screen_name,uni_handle
0,0,[KathuaRape],2019-06-08 19:45:56,The humanities department of @iitbombay had co...,ajhay9,NaN
1,1,[],2019-06-08 19:12:35,"iit bombay problem heard , which salt is good ...",satishgmatt,NaN
2,2,[],2019-06-08 19:12:05,The energy burden that goes unaudited. Our wor...,ronitabardhan,NaN
3,3,[],2019-06-08 18:59:07,Dr. Puniyani is great and will fight for truth...,ChackoattukadJ,NaN
4,4,"[microplastics, worldoceansday]",2019-06-08 18:17:58,The study of @iitbombay shows that every brand...,CitizenKamran,NaN
...,...,...,...,...,...,...
49081,2138,[],2020-06-10 01:00:25,Time to talk with New Yorker's on Social Dista...,prjeusa,NaN
49082,2139,[],2020-06-10 00:32:20,"IIT Bombay is India’s top university, says 202...",DrRahul_G,NaN
49083,2140,[],2020-06-10 00:30:22,from the abstract of this paper i have no idea...,jc96531326,NaN
49084,2141,[],2020-06-10 00:17:39,That's a hella small sample size and a pretty ...,Techbropolis,NaN
49085,2142,[SARSCov2],2020-06-10 00:15:48,"Marked differences in survival, drying time fo...",EricTopol,NaN

In [41]:
iitb[iitb['uni_handle'] == 1]

,index,hashtags,timestamp,text,screen_name,uni_handle
58,58,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1.0
77,77,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1.0
141,141,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1.0
142,142,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1.0
226,226,[],2019-06-27 05:13:39,In order to create more awareness about solar ...,iitbombay,1.0
...,...,...,...,...,...,...
47391,448,[],2020-06-15 08:30:14,E-Cell IIT Bombay is proud to host a webinar w...,ecell_iitb,1.0
47701,758,[],2020-06-06 07:32:14,Kudos to team from IIT Bombay!\nhttps://www.hi...,iitbombay,1.0
48167,1224,[Proud_to_be_Indianpic],2020-06-12 11:53:56,"E-Cell, IIT Bombay congratulates Kiran Mazumda...",ecell_iitb,1.0
48480,1537,"[Connect_Learn_Grow, CAProgramLaunched, Regist...",2020-06-03 06:47:18,Presenting the E-Cell IIT Bombay's Campus Amba...,ecell_iitb,1.0
48659,1716,[],2020-06-11 09:19:45,IIT Bombay is ranked 3rd in engineering catego...,iitbombay,1.0

In [42]:
iitb['uni_handle'] = iitb['uni_handle'].replace(np.nan, 0)

In [43]:
iitb[iitb['uni_handle'] == 1]

,index,hashtags,timestamp,text,screen_name,uni_handle
58,58,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1.0
77,77,[],2019-06-10 04:36:29,IIT Bombay congratulates our alumnus Mr. Abida...,iitbombay,1.0
141,141,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1.0
142,142,[],2019-06-18 05:01:00,"Professor Sridhar Balasubramanian, an associat...",iitbombay,1.0
226,226,[],2019-06-27 05:13:39,In order to create more awareness about solar ...,iitbombay,1.0
...,...,...,...,...,...,...
47391,448,[],2020-06-15 08:30:14,E-Cell IIT Bombay is proud to host a webinar w...,ecell_iitb,1.0
47701,758,[],2020-06-06 07:32:14,Kudos to team from IIT Bombay!\nhttps://www.hi...,iitbombay,1.0
48167,1224,[Proud_to_be_Indianpic],2020-06-12 11:53:56,"E-Cell, IIT Bombay congratulates Kiran Mazumda...",ecell_iitb,1.0
48480,1537,"[Connect_Learn_Grow, CAProgramLaunched, Regist...",2020-06-03 06:47:18,Presenting the E-Cell IIT Bombay's Campus Amba...,ecell_iitb,1.0
48659,1716,[],2020-06-11 09:19:45,IIT Bombay is ranked 3rd in engineering catego...,iitbombay,1.0

In [45]:
#dataframe containing additional column uni_handle (1 if it is a handle of the university else 0)
#iitm[iitm['uni_handle'] == 0]

NameError: name 'iitb_final' is not defined

In [47]:
#Finding sentiment of the tweets using VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
iitb['compound'] = [analyzer.polarity_scores(v)['compound'] for v in iitb['text']]

In [34]:
iitb

,Tweet_text,date,username,retweets,uni_handle,compound
0,"#OnThisDay in 1831, James Clerk Maxwell was bo...",2020-06-13 13:36:43+00:00,Techfest_IITB,19,0.0,0.6369
1,This being the only courier service in the are...,2020-06-13 13:31:12+00:00,Karthik38561419,0,0.0,0.3612
2,And QS world University ranking to standing of...,2020-06-13 11:44:07+00:00,Ashutos55613937,0,0.0,0.0000
3,Please Help Us #Students .Please extend Date o...,2020-06-13 11:27:36+00:00,Himansh18811460,1,0.0,0.8519
4,@Techfest_IITB remembers Dr. John Forbes Nash ...,2020-06-13 11:11:54+00:00,Techfest_IITB,28,0.0,0.0000
...,...,...,...,...,...,...
11936,TIME PASS.... Ask them to quit IIM and then pr...,2020-01-01 05:36:16+00:00,hemmu25,0,0.0,-0.2500
11937,Must watch. Epic! https://youtu.be/CEpRccgc9G0...,2020-01-01 04:57:35+00:00,ApoorvanandJ,0,0.0,0.0000
11938,"yes, IIT D, IIT BOMBAY, IIT MADRAS, IIT KANPUR...",2020-01-01 04:52:50+00:00,ProudToBeJamian,0,0.0,0.9167
11939,IIT Bombay Beckons you to attend an alumni reu...,2020-01-01 03:37:30+00:00,debeshchoudhury,0,0.0,0.6166
11940,When will India develop this advanced weapons?...,2020-01-01 00:31:00+00:00,rewatiramanray,0,0.0,0.2240

In [50]:
#classifying sentiments as positive,negative and neutral
def sentiment(compound):
    res = ""
    if(compound >= 0.05):
        res="Positive"
    elif(compound <= - 0.05):
        res="Negative"
    else:
        res="Neutral"
    return res

iitb['Sentiment'] = iitb['compound'].apply(lambda x: sentiment(x))

In [51]:
iitb

,index,hashtags,timestamp,text,screen_name,uni_handle,compound,Sentiment
0,0,[KathuaRape],2019-06-08 19:45:56,The humanities department of @iitbombay had co...,ajhay9,0.0,-0.6369,Negative
1,1,[],2019-06-08 19:12:35,"iit bombay problem heard , which salt is good ...",satishgmatt,0.0,0.7003,Positive
2,2,[],2019-06-08 19:12:05,The energy burden that goes unaudited. Our wor...,ronitabardhan,0.0,-0.2023,Negative
3,3,[],2019-06-08 18:59:07,Dr. Puniyani is great and will fight for truth...,ChackoattukadJ,0.0,0.9300,Positive
4,4,"[microplastics, worldoceansday]",2019-06-08 18:17:58,The study of @iitbombay shows that every brand...,CitizenKamran,0.0,-0.7906,Negative
...,...,...,...,...,...,...,...,...
49081,2138,[],2020-06-10 01:00:25,Time to talk with New Yorker's on Social Dista...,prjeusa,0.0,0.0000,Neutral
49082,2139,[],2020-06-10 00:32:20,"IIT Bombay is India’s top university, says 202...",DrRahul_G,0.0,0.2023,Positive
49083,2140,[],2020-06-10 00:30:22,from the abstract of this paper i have no idea...,jc96531326,0.0,-0.2960,Negative
49084,2141,[],2020-06-10 00:17:39,That's a hella small sample size and a pretty ...,Techbropolis,0.0,0.2263,Positive
49085,2142,[SARSCov2],2020-06-10 00:15:48,"Marked differences in survival, drying time fo...",EricTopol,0.0,-0.4939,Negative

In [52]:
iitb.to_csv('final_iitb.csv',index=False)

11941