In [1]:
import json
import csv
import tweepy
import re
import nltk
from nltk.stem import WordNetLemmatizer
import pandas as pd
import GetOldTweets3 as got
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()
import numpy as np

In [2]:
consumer_key = input()
consumer_secret = input()
access_key = input()
access_secret = input()

BZCiEnipIjwlIr5qdFawFL7Ka
UTHnBo6nzb5HhsQGoFxjEHBHArDAlT9VyXx8x98AObzpV6iArr
757468675414695936-wVM842i23t6yTUDhbwuKkH92LGnZRAq
TEFpzrCMH8aYl7YURiygG6Mgk76BAM9tLNWagI8JBAHiZ

In [3]:
#scrape tweets with keyword "iitmadras" with columns text,date,username and retweets
text_query = 'iitdelhi'
since_date = '2020-01-01'
# Creation of query object
tweetCriteria = got.manager.TweetCriteria().setQuerySearch(text_query).setSince(since_date).setLang('en')
# Creation of list that contains all tweets
tw = got.manager.TweetManager.getTweets(tweetCriteria)
# Creating list of chosen tweet data
text_tweets = [[tweet.text ,tweet.date,tweet.username,tweet.retweets] for tweet in tw]

In [4]:
len(text_tweets)

10420

In [7]:
tweets_df = pd.DataFrame(text_tweets)
tweets_df=tweets_df.drop_duplicates()

In [8]:
tweets_df

,0,1,2,3
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1
...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0

In [9]:
tweets_df.columns = ['Tweet_text' , 'date' , 'username','retweets']

In [10]:
tweets_df

,Tweet_text,date,username,retweets
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1
...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0

In [11]:
#check how many tweets were from one of the university handles
uni_tweets = tweets_df.loc[tweets_df['username'].isin(['iitdelhi'])]

In [12]:
uni_tweets['uni_handle'] = 1

C:\Users\KIRHIKAGURUMURTHY\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
uni_tweets
#uni_handle_list =  ['iitmadras','ecelliitm','vandemataramiit','iGEM_IITM','iitm_respark','domsiitmadras','emliitm','iitmbt','CFI_IITM','iitmfoundation']

,Tweet_text,date,username,retweets,uni_handle
277,"Prof. Rao added, ""We also want to see our tech...",2020-06-11 13:22:05+00:00,iitdelhi,4,1
278,#IndiaRankings2020 (NIRF): #IITDelhi bags 2nd ...,2020-06-11 13:21:56+00:00,iitdelhi,34,1
476,(1/2) WATCH- 'IIT Delhi to focus on Aatmnirbha...,2020-06-11 04:15:52+00:00,iitdelhi,15,1
776,#IITDelhi to focus on #AatmNirbharBharat More ...,2020-06-10 08:48:25+00:00,iitdelhi,7,1
785,Here's a glimpse of some initiatives that cont...,2020-06-10 07:26:38+00:00,iitdelhi,0,1
...,...,...,...,...,...
9992,A special lecture -â€œEntering the Era of Genomi...,2020-01-08 10:29:17+00:00,iitdelhi,3,1
10120,"Prof V. Ramgopal Rao, Director, IIT Delhi met ...",2020-01-06 15:19:34+00:00,iitdelhi,4,1
10242,"IIT-Delhi researcher develops low-cost ""fabric...",2020-01-05 06:26:38+00:00,iitdelhi,6,1
10381,Product Realization is an experiential learnin...,2020-01-02 12:34:15+00:00,iitdelhi,1,1
10391,#IITDelhi researchers led by Prof Apurba Das h...,2020-01-02 06:14:45+00:00,iitdelhi,9,1

In [14]:
tweets_df['uni_handle'] = uni_tweets['uni_handle']

In [15]:
iitd = tweets_df.combine_first(tweets_df)
iitd

,Tweet_text,date,username,retweets,uni_handle
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0,NaN
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0,NaN
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0,NaN
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0,NaN
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1,NaN
...,...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0,NaN
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0,NaN
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9,NaN
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1,NaN
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0,NaN

In [16]:
iitd[iitd['uni_handle'] == 1]

,Tweet_text,date,username,retweets,uni_handle
277,"Prof. Rao added, ""We also want to see our tech...",2020-06-11 13:22:05+00:00,iitdelhi,4,1.0
278,#IndiaRankings2020 (NIRF): #IITDelhi bags 2nd ...,2020-06-11 13:21:56+00:00,iitdelhi,34,1.0
476,(1/2) WATCH- 'IIT Delhi to focus on Aatmnirbha...,2020-06-11 04:15:52+00:00,iitdelhi,15,1.0
776,#IITDelhi to focus on #AatmNirbharBharat More ...,2020-06-10 08:48:25+00:00,iitdelhi,7,1.0
785,Here's a glimpse of some initiatives that cont...,2020-06-10 07:26:38+00:00,iitdelhi,0,1.0
...,...,...,...,...,...
9992,A special lecture -â€œEntering the Era of Genomi...,2020-01-08 10:29:17+00:00,iitdelhi,3,1.0
10120,"Prof V. Ramgopal Rao, Director, IIT Delhi met ...",2020-01-06 15:19:34+00:00,iitdelhi,4,1.0
10242,"IIT-Delhi researcher develops low-cost ""fabric...",2020-01-05 06:26:38+00:00,iitdelhi,6,1.0
10381,Product Realization is an experiential learnin...,2020-01-02 12:34:15+00:00,iitdelhi,1,1.0
10391,#IITDelhi researchers led by Prof Apurba Das h...,2020-01-02 06:14:45+00:00,iitdelhi,9,1.0

In [17]:
iitd['uni_handle'] = iitd['uni_handle'].replace(np.nan, 0)

In [18]:
iitd[iitd['uni_handle'] == 1]

,Tweet_text,date,username,retweets,uni_handle
277,"Prof. Rao added, ""We also want to see our tech...",2020-06-11 13:22:05+00:00,iitdelhi,4,1.0
278,#IndiaRankings2020 (NIRF): #IITDelhi bags 2nd ...,2020-06-11 13:21:56+00:00,iitdelhi,34,1.0
476,(1/2) WATCH- 'IIT Delhi to focus on Aatmnirbha...,2020-06-11 04:15:52+00:00,iitdelhi,15,1.0
776,#IITDelhi to focus on #AatmNirbharBharat More ...,2020-06-10 08:48:25+00:00,iitdelhi,7,1.0
785,Here's a glimpse of some initiatives that cont...,2020-06-10 07:26:38+00:00,iitdelhi,0,1.0
...,...,...,...,...,...
9992,A special lecture -â€œEntering the Era of Genomi...,2020-01-08 10:29:17+00:00,iitdelhi,3,1.0
10120,"Prof V. Ramgopal Rao, Director, IIT Delhi met ...",2020-01-06 15:19:34+00:00,iitdelhi,4,1.0
10242,"IIT-Delhi researcher develops low-cost ""fabric...",2020-01-05 06:26:38+00:00,iitdelhi,6,1.0
10381,Product Realization is an experiential learnin...,2020-01-02 12:34:15+00:00,iitdelhi,1,1.0
10391,#IITDelhi researchers led by Prof Apurba Das h...,2020-01-02 06:14:45+00:00,iitdelhi,9,1.0

In [19]:
#dataframe containing additional column uni_handle (1 if it is a handle of the university else 0)
#iitm[iitm['uni_handle'] == 0] 
iitd_final = iitd.drop_duplicates()
iitd_final

,Tweet_text,date,username,retweets,uni_handle
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0,0.0
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0,0.0
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0,0.0
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0,0.0
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1,0.0
...,...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0,0.0
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0,0.0
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9,0.0
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1,0.0
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0,0.0

In [20]:
#Finding sentiment of the tweets using VADER
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
iitd['compound'] = [analyzer.polarity_scores(v)['compound'] for v in iitd['Tweet_text']]

In [21]:
iitd

,Tweet_text,date,username,retweets,uni_handle,compound
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0,0.0,0.5423
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0,0.0,0.9300
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0,0.0,0.5106
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0,0.0,0.0000
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1,0.0,0.0516
...,...,...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0,0.0,0.0000
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0,0.0,0.0000
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9,0.0,0.4019
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1,0.0,0.7896
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0,0.0,0.6486

In [22]:
#classifying sentiments as positive,negative and neutral
def sentiment(compound):
    res = ""
    if(compound >= 0.05):
        res="Positive"
    elif(compound <= - 0.05):
        res="Negative"
    else:
        res="Neutral"
    return res

iitd['Sentiment'] = iitd['compound'].apply(lambda x: sentiment(x))

In [23]:
iitd

,Tweet_text,date,username,retweets,uni_handle,compound,Sentiment
0,The valuation subject should be post graduate ...,2020-06-12 14:45:07+00:00,shekhargupta68,0,0.0,0.5423,Positive
1,@ProfSushmaGupta @drharshvardhan @narendramodi...,2020-06-12 14:45:02+00:00,ProfSushmaGupta,0,0.0,0.9300,Positive
2,"Program: ""Nano-particles of PTFE as Extreme-pr...",2020-06-12 14:35:08+00:00,DucomTribos,0,0.0,0.5106,Positive
3,It's as real as #sunrises in the #east,2020-06-12 14:28:26+00:00,raj_knp,0,0.0,0.0000,Neutral
4,"ROPOSO- founders : Mayank, Avinash,kaushal (gr...",2020-06-12 14:28:21+00:00,Sanidhya29jhs,1,0.0,0.0516,Positive
...,...,...,...,...,...,...,...
10415,Ya productive people don't go @jamiamillia_ Un...,2020-01-01 09:24:09+00:00,thesahilb,0,0.0,0.0000,Neutral
10416,Any job vacancy there ? I am from PWD category,2020-01-01 09:12:24+00:00,tanmaymalik555,0,0.0,0.0000,Neutral
10417,.@iitdelhi #researchers develop #fabric feel t...,2020-01-01 08:54:30+00:00,IndiaDST,9,0.0,0.4019,Positive
10418,DMS Family wishes everyone a prosperous New Ye...,2020-01-01 08:27:18+00:00,DMSIITD,1,0.0,0.7896,Positive
10419,CUSB wishes Happy New Year 2020.,2020-01-01 06:37:52+00:00,CUSBofficial,0,0.0,0.6486,Positive

In [35]:
iitd.to_csv('final_iitm.csv')